project_id = "ovhuafsxhdbhaqccfpmt"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.fetch-ga4-analytics]
verify_jwt = true

[functions.freepik-api]
verify_jwt = true

[functions.submit-contact-form]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = true

[functions.publish-blog-post]
verify_jwt = true